<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        // ── 1. Outlet utama ──────────────────────────────────────────
        $outletId = DB::table('outlets')->insertGetId([
            'name'       => 'Toko Utama',
            'address'    => 'Jl. Contoh No. 1',
            'phone'      => '08123456789',
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        // ── 2. Users (via UserSeeder) ─────────────────────────────────
        $this->call(UserSeeder::class);

        // ── 3. Kategori produk ───────────────────────────────────────
        DB::table('categories')->insert([
            ['name' => 'Minuman',    'description' => 'Produk minuman',         'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Makanan',    'description' => 'Produk makanan',         'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Snack',      'description' => 'Camilan dan snack',      'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kebersihan', 'description' => 'Produk kebersihan',      'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lainnya',    'description' => 'Produk kategori lain',   'created_at' => now(), 'updated_at' => now()],
        ]);

        // ── 4. Kategori pengeluaran ──────────────────────────────────
        DB::table('expense_categories')->insert([
            ['name' => 'Listrik',      'description' => 'Tagihan listrik',          'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Air',          'description' => 'Tagihan air',              'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Gaji',         'description' => 'Gaji karyawan',            'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sewa',         'description' => 'Biaya sewa tempat',        'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bahan Baku',   'description' => 'Pembelian bahan baku',     'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Transportasi', 'description' => 'Biaya transportasi',       'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lainnya',      'description' => 'Pengeluaran lain-lain',    'created_at' => now(), 'updated_at' => now()],
        ]);

        // ── 5. Produk Dummy (Sinkron dengan Model Product BE & FE) ───
        $minumanId = DB::table('categories')->where('name', 'Minuman')->value('id') ?? 1;
        $makananId = DB::table('categories')->where('name', 'Makanan')->value('id') ?? 2;
        $snackId   = DB::table('categories')->where('name', 'Snack')->value('id') ?? 3;

        DB::table('products')->insert([
            // MINUMAN (Category: Minuman, Unit: cup)
            [
                'outlet_id'      => $outletId,
                'category_id'    => $minumanId,
                'name'           => 'Kopi Hitam',
                'sku'            => 'COF-BLK',
                'unit'           => 'cup',
                'purchase_price' => 3000.00,
                'selling_price'  => 8000.00,
                'stock_qty'      => 50,
                'stock_minimum'  => 10,
                'is_active'      => true,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'outlet_id'      => $outletId,
                'category_id'    => $minumanId,
                'name'           => 'Es Kopi Susu',
                'sku'            => 'COF-MILK',
                'unit'           => 'cup',
                'purchase_price' => 5000.00,
                'selling_price'  => 12000.00,
                'stock_qty'      => 40,
                'stock_minimum'  => 10,
                'is_active'      => true,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'outlet_id'      => $outletId,
                'category_id'    => $minumanId,
                'name'           => 'Cappuccino',
                'sku'            => 'COF-CAP',
                'unit'           => 'cup',
                'purchase_price' => 6000.00,
                'selling_price'  => 15000.00,
                'stock_qty'      => 30,
                'stock_minimum'  => 5,
                'is_active'      => true,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'outlet_id'      => $outletId,
                'category_id'    => $minumanId,
                'name'           => 'Caramel Latte',
                'sku'            => 'COF-CRM',
                'unit'           => 'cup',
                'purchase_price' => 7000.00,
                'selling_price'  => 18000.00,
                'stock_qty'      => 25,
                'stock_minimum'  => 5,
                'is_active'      => true,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'outlet_id'      => $outletId,
                'category_id'    => $minumanId,
                'name'           => 'Vanilla Latte',
                'sku'            => 'COF-VNL',
                'unit'           => 'cup',
                'purchase_price' => 7000.00,
                'selling_price'  => 18000.00,
                'stock_qty'      => 25,
                'stock_minimum'  => 5,
                'is_active'      => true,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'outlet_id'      => $outletId,
                'category_id'    => $minumanId,
                'name'           => 'Kopi Gula Aren',
                'sku'            => 'COF-AREN',
                'unit'           => 'cup',
                'purchase_price' => 5000.00,
                'selling_price'  => 13000.00,
                'stock_qty'      => 45,
                'stock_minimum'  => 10,
                'is_active'      => true,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'outlet_id'      => $outletId,
                'category_id'    => $minumanId,
                'name'           => 'Mochaccino',
                'sku'            => 'COF-MOC',
                'unit'           => 'cup',
                'purchase_price' => 6000.00,
                'selling_price'  => 16000.00,
                'stock_qty'      => 20,
                'stock_minimum'  => 5,
                'is_active'      => true,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'outlet_id'      => $outletId,
                'category_id'    => $minumanId,
                'name'           => 'Kopi Pandan',
                'sku'            => 'COF-PDN',
                'unit'           => 'cup',
                'purchase_price' => 6000.00,
                'selling_price'  => 15000.00,
                'stock_qty'      => 20,
                'stock_minimum'  => 5,
                'is_active'      => true,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'outlet_id'      => $outletId,
                'category_id'    => $minumanId,
                'name'           => 'Kopi Butterscotch',
                'sku'            => 'COF-BSC',
                'unit'           => 'cup',
                'purchase_price' => 7000.00,
                'selling_price'  => 18000.00,
                'stock_qty'      => 15,
                'stock_minimum'  => 5,
                'is_active'      => true,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],

            // MAKANAN (Category: Makanan, Unit: porsi)
            [
                'outlet_id'      => $outletId,
                'category_id'    => $makananId,
                'name'           => 'Nasi Goreng',
                'sku'            => 'FST-NAS',
                'unit'           => 'porsi',
                'purchase_price' => 8000.00,
                'selling_price'  => 15000.00,
                'stock_qty'      => 35,
                'stock_minimum'  => 5,
                'is_active'      => true,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'outlet_id'      => $outletId,
                'category_id'    => $makananId,
                'name'           => 'Mie Goreng / Mie Kuah',
                'sku'            => 'FST-MIE',
                'unit'           => 'porsi',
                'purchase_price' => 6000.00,
                'selling_price'  => 12000.00,
                'stock_qty'      => 40,
                'stock_minimum'  => 5,
                'is_active'      => true,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'outlet_id'      => $outletId,
                'category_id'    => $makananId,
                'name'           => 'Seblak',
                'sku'            => 'FST-SEB',
                'unit'           => 'porsi',
                'purchase_price' => 7000.00,
                'selling_price'  => 14000.00,
                'stock_qty'      => 30,
                'stock_minimum'  => 5,
                'is_active'      => true,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],

            // SNACK (Category: Snack, Unit: porsi)
            [
                'outlet_id'      => $outletId,
                'category_id'    => $snackId,
                'name'           => 'Kentang Goreng',
                'sku'            => 'SNK-KTG',
                'unit'           => 'porsi',
                'purchase_price' => 6000.00,
                'selling_price'  => 12000.00,
                'stock_qty'      => 30,
                'stock_minimum'  => 5,
                'is_active'      => true,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'outlet_id'      => $outletId,
                'category_id'    => $snackId,
                'name'           => 'Cireng',
                'sku'            => 'SNK-CRG',
                'unit'           => 'porsi',
                'purchase_price' => 4000.00,
                'selling_price'  => 8000.00,
                'stock_qty'      => 2, // Memicu low stock warning
                'stock_minimum'  => 5,
                'is_active'      => true,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'outlet_id'      => $outletId,
                'category_id'    => $snackId,
                'name'           => 'Cimol',
                'sku'            => 'SNK-CML',
                'unit'           => 'porsi',
                'purchase_price' => 3000.00,
                'selling_price'  => 6000.00,
                'stock_qty'      => 3, // Memicu low stock warning
                'stock_minimum'  => 5,
                'is_active'      => true,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'outlet_id'      => $outletId,
                'category_id'    => $snackId,
                'name'           => 'Cilor',
                'sku'            => 'SNK-CLR',
                'unit'           => 'porsi',
                'purchase_price' => 4000.00,
                'selling_price'  => 8000.00,
                'stock_qty'      => 25,
                'stock_minimum'  => 5,
                'is_active'      => true,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'outlet_id'      => $outletId,
                'category_id'    => $snackId,
                'name'           => 'Tahu Crispy',
                'sku'            => 'SNK-THC',
                'unit'           => 'porsi',
                'purchase_price' => 4000.00,
                'selling_price'  => 8000.00,
                'stock_qty'      => 20,
                'stock_minimum'  => 5,
                'is_active'      => true,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'outlet_id'      => $outletId,
                'category_id'    => $snackId,
                'name'           => 'Pisang Goreng',
                'sku'            => 'SNK-PSG',
                'unit'           => 'porsi',
                'purchase_price' => 4000.00,
                'selling_price'  => 8000.00,
                'stock_qty'      => 35,
                'stock_minimum'  => 5,
                'is_active'      => true,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'outlet_id'      => $outletId,
                'category_id'    => $snackId,
                'name'           => 'Pisang Coklat',
                'sku'            => 'SNK-PSC',
                'unit'           => 'porsi',
                'purchase_price' => 5000.00,
                'selling_price'  => 10000.00,
                'stock_qty'      => 15,
                'stock_minimum'  => 5,
                'is_active'      => true,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'outlet_id'      => $outletId,
                'category_id'    => $snackId,
                'name'           => 'Roti Bakar',
                'sku'            => 'SNK-RTB',
                'unit'           => 'porsi',
                'purchase_price' => 6000.00,
                'selling_price'  => 12000.00,
                'stock_qty'      => 25,
                'stock_minimum'  => 5,
                'is_active'      => true,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'outlet_id'      => $outletId,
                'category_id'    => $snackId,
                'name'           => 'Dimsum',
                'sku'            => 'SNK-DIM',
                'unit'           => 'porsi',
                'purchase_price' => 6000.00,
                'selling_price'  => 12000.00,
                'stock_qty'      => 4, // Memicu low stock warning
                'stock_minimum'  => 5,
                'is_active'      => true,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'outlet_id'      => $outletId,
                'category_id'    => $snackId,
                'name'           => 'Sosis Bakar',
                'sku'            => 'SNK-SSB',
                'unit'           => 'porsi',
                'purchase_price' => 4000.00,
                'selling_price'  => 8000.00,
                'stock_qty'      => 30,
                'stock_minimum'  => 5,
                'is_active'      => true,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
        ]);
    }
}
